# 作業目標:

    使用CIFAR100, 數據集變大的影響
    
    
# 作業重點:¶

   了解 CIFAR100 跟 CIFAR10 數據及差異


In [1]:
import numpy
from keras.datasets import cifar100
import numpy as np
np.random.seed( 100 )  

Using TensorFlow backend.


# 資料準備

In [2]:
( x_img_train, y_label_train ), ( x_img_test, y_label_test ) = cifar100.load_data( )  

print( 'Train Data : ', len( x_img_train ) )
print( 'Test Data : ', len( x_img_test ) )

Train Data :  50000
Test Data :  10000


In [3]:
# 查詢檔案維度資訊

print( 'Shape of Train : ',  x_img_train.shape )
print( 'Shape of Train Label : ',  y_label_train.shape )  
print( 'Shape of Test : ',  x_img_test.shape )  
print( 'Shape of Test Label : ',  y_label_test.shape )  

Shape of Train :  (50000, 32, 32, 3)
Shape of Train Label :  (50000, 1)
Shape of Test :  (10000, 32, 32, 3)
Shape of Test Label :  (10000, 1)


# Image Normalize 

In [4]:
x_img_train[2][2][2]

array([250, 245, 233], dtype=uint8)

In [5]:
x_img_train_normalize = x_img_train.astype( 'float32' ) / 255.0
x_img_test_normalize = x_img_test.astype( 'float32' ) / 255.0

In [6]:
x_img_train_normalize[2][2][2]

array([0.98039216, 0.9607843 , 0.9137255 ], dtype=float32)

# 轉換 Label 為 OneHot Encoding 
    * 註：CIFAR100 標註 100 個類別

In [7]:
y_label_train.shape

(50000, 1)

In [8]:
# 前20筆資料的類別
y_label_train[ : 20 ]  

array([[19],
       [29],
       [ 0],
       [11],
       [ 1],
       [86],
       [90],
       [28],
       [23],
       [31],
       [39],
       [96],
       [82],
       [17],
       [71],
       [39],
       [ 8],
       [97],
       [80],
       [71]])

In [9]:
from keras.utils import np_utils 

y_label_train_OneHot = np_utils.to_categorical( y_label_train )
y_label_test_OneHot = np_utils.to_categorical( y_label_test )

In [10]:
# After OneHot Encoding 
y_label_train_OneHot.shape

(50000, 100)

In [11]:
# After OneHot Encoding 
y_label_train_OneHot[ : 5 ]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.