## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則話來觀察訓練情形。

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn import datasets, linear_model
#from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.linear_model import Lasso, Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score


In [2]:
boston = datasets.load_boston( )

In [3]:
boston.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [4]:
boston.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

### 線性迴歸模型

In [5]:
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split( boston.data , boston.target, test_size = 0.1, random_state = 4 )

# 建立一個線性回歸模型
lreg = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
lreg.fit( x_train, y_train )

# 將測試資料丟進模型得到預測結果
y_pred = lreg.predict( x_test )

# 評估模型
print( "Mean squared error: %.2f" 
      % mean_squared_error( y_test, y_pred ) )

Mean squared error: 17.04


In [6]:
# 線性迴歸模型的參數
lreg.coef_

array([-1.25856659e-01,  4.84257396e-02,  1.84085281e-02,  3.08509569e+00,
       -1.73277018e+01,  3.61674713e+00,  2.19181853e-03, -1.49361132e+00,
        3.19979200e-01, -1.27294649e-02, -9.27469086e-01,  9.50912468e-03,
       -5.33592471e-01])

### Lasso

In [7]:
# 建立 Lasso 迴歸模型
Lasso = linear_model.Lasso( alpha = 0.005 )

# 將訓練資料丟進去模型訓練
Lasso.fit( x_train, y_train )

# 將測試資料丟進模型得到預測結果
y_pred = Lasso.predict( x_test )

# 預測值與實際值的差距，使用 MSE
print( "Mean squared error: %.2f"
      % mean_squared_error( y_test, y_pred ) )

Mean squared error: 17.06


In [8]:
# 印出各特徵對應的係數
Lasso.coef_

array([-1.24969153e-01,  4.86611171e-02,  1.14751370e-02,  2.98354372e+00,
       -1.56254210e+01,  3.62098622e+00,  8.02904862e-04, -1.46775139e+00,
        3.15900969e-01, -1.28507255e-02, -9.09975964e-01,  9.59237088e-03,
       -5.36669172e-01])

### Ridge

In [9]:
# 建立 Ridge 迴歸模型
Ridge = linear_model.Ridge( alpha = 0.005 )

# 將訓練資料丟進去模型訓練
Ridge.fit( x_train, y_train )

# 將測試資料丟進模型得到預測結果
y_pred = Ridge.predict( x_test )

# 預測值與實際值的差距，使用 MSE
print( "Mean squared error: %.2f"
      % mean_squared_error( y_test, y_pred ) )

Mean squared error: 17.04


In [10]:
# 印出 Ridge 的參數
Ridge.coef_

array([-1.25827156e-01,  4.84348305e-02,  1.81486748e-02,  3.08377066e+00,
       -1.72650924e+01,  3.61727578e+00,  2.13381411e-03, -1.49272002e+00,
        3.19821824e-01, -1.27334662e-02, -9.26813880e-01,  9.51221747e-03,
       -5.33670643e-01])